# Generated by Django 6.0.2 on 2026-02-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categary',
            new_name='category',
        ),
    ]
